In [9]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H,n_W,n_C = 32,28,28,1
n_filter = 10
k_size = 3

images = tf.random.uniform(minval=0,maxval=1,shape=(N,n_H,n_W,n_C))

conv = Conv2D(filters= n_filter,kernel_size=k_size)
Y = conv(images)

W,B = conv.get_weights()

print(images.shape)
print(Y.shape)
print(W.shape)
print(B.shape)

(32, 28, 28, 1)
(32, 26, 26, 10)
(3, 3, 1, 10)
(10,)


In [11]:
import tensorflow as tf

import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H,n_W,n_C = 1,5,5,1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0,maxval=1,shape=(N,n_H,n_W,n_C))

conv = Conv2D(filters= n_filter,kernel_size=k_size)
y = conv(images)

W,B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H-k_size+1,n_W - k_size +1))
for i in range(n_H-k_size+1):
    for j in range(n_W-k_size+1):
        window =images[i: i+k_size,j:j+k_size]
        y_man[i,j] = np.sum(window *W) +B

print("Y(Tensorflow): \n",y.numpy().squeeze())
print("Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[0.6499023  0.9885416  0.91854525]
 [0.93147814 0.9390447  0.71749395]
 [0.9859815  1.2124313  0.7044133 ]]
Y(Manual): 
 [[0.64990228 0.9885416  0.91854525]
 [0.93147808 0.93904471 0.71749389]
 [0.98598152 1.21243143 0.70441341]]


In [12]:
import tensorflow as tf

import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H,n_W,n_C = 1,5,5,3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0,maxval=1,shape=(N,n_H,n_W,n_C))

conv = Conv2D(filters= n_filter,kernel_size=k_size)
y = conv(images)

W,B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H-k_size+1,n_W - k_size +1))
for i in range(n_H-k_size+1):
    for j in range(n_W-k_size+1):
        window =images[i: i+k_size,j:j+k_size,:]
        y_man[i,j] = np.sum(window *W) +B

print("Y(Tensorflow): \n",y.numpy().squeeze())
print("Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[-1.1840842  -0.80515695 -0.11530058]
 [-0.7048601  -0.713936   -0.91624314]
 [-0.23668197 -0.5807859  -0.18160482]]
Y(Manual): 
 [[-1.18408418 -0.80515707 -0.11530055]
 [-0.70486003 -0.71393597 -0.91624314]
 [-0.23668197 -0.58078581 -0.18160479]]
