In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N,n_feature = 4,10
X =  tf.random.normal(shape=(N,n_feature))

n_neurons = [3,5]
dense1 = Dense(units=n_neurons[0],activation='sigmoid')
dense2 = Dense(units=n_neurons[1],activation='sigmoid')

A1 = dense1(X)
Y = dense2(A1)

W1,B1 = dense1.get_weights()
W2,B2 = dense2.get_weights()

print("x: {}\n".format(X.shape))

print("W1: " ,W1.shape)
print("B1: " ,B1.shape)
print("W1: {}\n".format(A1.shape))


print("W2: " ,W2.shape)
print("B2: " ,B2.shape)
print("Y: {}\n".format(Y.shape))

x: (4, 10)

W1:  (10, 3)
B1:  (3,)
W1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)



In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N,n_feature = 4,10
X =  tf.random.normal(shape=(N,n_feature))

n_neurons = [10,20,30,40,50]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron,activation='relu')
    dense_layers.append(dense)
 

print("Input : ", X.shape)
for dense_idx,dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer ", dense_idx+1)
    print(X.shape,'\n')

Y = X



Input :  (4, 10)
After dense layer  1
(4, 10) 

After dense layer  2
(4, 20) 

After dense layer  3
(4, 30) 

After dense layer  4
(4, 40) 

After dense layer  5
(4, 50) 

tf.Tensor(
[[0.         0.         0.07266553 0.09094662 0.         0.04725067
  0.         0.         0.0238998  0.00097612 0.1732813  0.15287597
  0.02096145 0.         0.         0.03297299 0.         0.07283218
  0.04792618 0.         0.         0.09899933 0.08888899 0.1257076
  0.         0.07417672 0.00369863 0.06723648 0.02680386 0.
  0.         0.         0.11951188 0.05670055 0.06635094 0.03071807
  0.         0.         0.         0.10313254 0.01790557 0.06036072
  0.13355944 0.06239726 0.11604962 0.05542528 0.05813009 0.
  0.         0.        ]
 [0.         0.00908747 0.02493665 0.         0.         0.00262961
  0.         0.         0.02101864 0.         0.00557991 0.01017244
  0.00486257 0.         0.         0.         0.         0.0286724
  0.03417176 0.01582202 0.         0.01082113 0.02189825 0.013

In [23]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N,n_feature = 4,10
X =  tf.random.normal(shape=(N,n_feature))
X_cp = tf.identity(X)

n_neurons = [3,4,5]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron,activation='sigmoid')
    dense_layers.append(dense)
 
#forward propagation(Tensorflow)
W,B = list(),list()
for dense_idx,dense in enumerate(dense_layers):
    X = dense(X)
    w,b = dense.get_weights()

    W.append(w)
    B.append(b)
print("Y(tensorflow): \n",X.numpy())

#forward propagation(Manual)

for layer_idx in range(len(n_neurons)):
    w,b = W[layer_idx],B[layer_idx]

    X_cp = matmul(X_cp,w) + b
    X_cp = 1/(1+exp(-X_cp))

print("Y(matmul): \n",X_cp.numpy())

Y(tensorflow): 
 [[0.44618598 0.7295002  0.48325834 0.5367152  0.46054727]
 [0.45286575 0.72648335 0.49110103 0.5482703  0.4553259 ]
 [0.4205274  0.7270896  0.47811317 0.5303647  0.47694746]
 [0.4379588  0.7335043  0.4825952  0.5381219  0.46162027]]
Y(matmul): 
 [[0.44618598 0.7295002  0.48325834 0.5367152  0.46054724]
 [0.45286575 0.72648335 0.491101   0.5482703  0.45532593]
 [0.4205274  0.7270895  0.47811314 0.5303647  0.47694746]
 [0.43795878 0.73350435 0.4825952  0.5381219  0.46162027]]
