In [49]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W ,n_C = 1,28,28,3

n_filter = 5
k_size = 3


images = tf.random.uniform(minval=0,maxval=1,shape=(N, n_H, n_W ,n_C))

conv = Conv2D(filters=n_filter,kernel_size=k_size)
Y = conv(images)

W,B = conv.get_weights()
print("Input Image: {} ".format(images.shape))
print("W/B: {} / {}".format(W.shape,B.shape))
print("Output Image: {}".format(Y.shape))

Input Image: (1, 28, 28, 3) 
W/B: (3, 3, 3, 5) / (5,)
Output Image: (1, 26, 26, 5)


In [50]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W ,n_C = 1,5,5,3

n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0,maxval=1,shape=(N, n_H, n_W ,n_C))

#forward propagation(Tensorflow)
conv = Conv2D(filters=n_filter,kernel_size=k_size)
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(),(2,0,1))
print("Y(Tensorflow): \n",Y)

W,B = conv.get_weights()
#forward propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H-k_size+1,n_W-k_size+1,n_filter))
for c in range(n_filter):
    c_W = W[:,:,:,c]
    c_b = B[c]

    for h in range(n_H-k_size+1):
        for w in range(n_W-k_size+1):
            window = images[h:h+k_size, w:w+k_size,:]
            conv = np.sum(window * c_W) + c_b

            Y_man[h,w,c] = conv

print("Y(Manual) : \n",np.transpose(Y_man,(2,0,1)))

Y(Tensorflow): 
 [[[-0.01284415  0.201962  ]
  [ 0.34034678  0.44952285]]

 [[-0.23522624 -0.53537136]
  [-0.9563875  -0.2318887 ]]

 [[-0.7102654  -0.15628472]
  [-0.13345513 -0.40705004]]]
Y(Manual) : 
 [[[-0.01284409  0.20196199]
  [ 0.34034675  0.44952291]]

 [[-0.23522626 -0.53537136]
  [-0.95638752 -0.23188862]]

 [[-0.7102654  -0.15628487]
  [-0.1334551  -0.40705001]]]


In [51]:
import numpy as np

images = np.random.randint(low=0,high=10,size=(2,3,4))
for c in range(4):
    print(images[:,:,c])

print("\n")
images = np.transpose(images,(2,0,1))
for c in range(4):
    print(images[c,:,:])

[[0 2 5]
 [3 8 9]]
[[3 7 3]
 [6 9 5]]
[[4 5 0]
 [8 5 1]]
[[8 7 4]
 [1 3 8]]


[[0 2 5]
 [3 8 9]]
[[3 7 3]
 [6 9 5]]
[[4 5 0]
 [8 5 1]]
[[8 7 4]
 [1 3 8]]


In [52]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W ,n_C = 1,5,5,3

n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0,maxval=1,shape=(N, n_H, n_W ,n_C))

#forward propagation(Tensorflow)
conv = Conv2D(filters=n_filter,kernel_size=k_size,activation='sigmoid')
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(),(2,0,1))
print("Y(Tensorflow): \n",Y)

W,B = conv.get_weights()
#forward propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H-k_size+1,n_W-k_size+1,n_filter))
for c in range(n_filter):
    c_W = W[:,:,:,c]
    c_b = B[c]

    for h in range(n_H-k_size+1):
        for w in range(n_W-k_size+1):
            window = images[h:h+k_size, w:w+k_size,:]
            conv = np.sum(window * c_W) + c_b
            conv = 1/(1+np.exp(-conv))

            Y_man[h,w,c] = conv

print("Y(Manual) : \n",np.transpose(Y_man,(2,0,1)))

Y(Tensorflow): 
 [[[0.45102155 0.4497645 ]
  [0.59133327 0.47316098]]

 [[0.5523621  0.3491673 ]
  [0.4384145  0.33552262]]

 [[0.6669626  0.3761655 ]
  [0.51579034 0.5085596 ]]]
Y(Manual) : 
 [[[0.45102155 0.44976447]
  [0.59133334 0.473161  ]]

 [[0.55236212 0.34916728]
  [0.43841452 0.3355226 ]]

 [[0.66696258 0.37616553]
  [0.5157904  0.50855963]]]
