In [3]:
# import tensorflow as tf
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.models import Sequential

# model = Sequential()
# model.add(Dense(units=10,activation='sigmoid'))
# model.add(Dense(units=5,activation='sigmoid'))

# x = tf.random.normal(shape=(10,5))
# Y = model(x)
# print(Y.numpy())

import tensorflow as tf
from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel,self).__init__()

        self.dense1 = Dense(units=10,activation='sigmoid')
        self.dense2 = Dense(units=5,activation='sigmoid')

    def call(self,x):
        x = self.dense1(x)
        x = self.dense2(x)

        return x

model = TestModel()
x = tf.random.normal(shape=(10,5))
Y = model(x)
print(Y.numpy())

[[0.647984   0.39031515 0.5856709  0.4293045  0.64463925]
 [0.6350725  0.39290577 0.5779692  0.4236553  0.64197165]
 [0.72553414 0.40193036 0.622813   0.53948313 0.60832286]
 [0.6164402  0.41064072 0.56025153 0.4264058  0.6353077 ]
 [0.73117733 0.40162337 0.6078461  0.5281081  0.6147623 ]
 [0.5649754  0.41692877 0.55841    0.4265915  0.61536944]
 [0.7546854  0.37714636 0.63980544 0.52800435 0.6217026 ]
 [0.6569638  0.3503343  0.59869236 0.43052083 0.6081152 ]
 [0.52307594 0.39787865 0.5785098  0.37455764 0.628831  ]
 [0.58064663 0.4313787  0.5240801  0.4004212  0.6433993 ]]


In [5]:
from tensorflow.keras.models import Model
import tensorflow as tf

class TestModel(Model):
    def __init__(self,n_neurons):
        super(TestModel,self).__init__()
        self.n_neurons = n_neurons

        self.dense_layers = list()
        for n_neuron in self.n_neurons:
            self.dense_layers.append(Dense(units=n_neuron,activation='sigmoid'))

    def call(self,x):
        for dense in self.dense_layers:
            x = dense(x)

            return x

n_neurons= [10,2,5,8]
model = TestModel(n_neurons)
x = tf.random.normal(shape=(8,5))
Y = model(x)

print(Y.numpy())




[[0.50942236 0.46283823 0.24579781 0.723213   0.64800566 0.6090378
  0.46496072 0.40097472 0.38078284 0.3459466 ]
 [0.58915544 0.37511444 0.48121387 0.37147778 0.7153793  0.6898574
  0.7734156  0.28420794 0.65587324 0.7854878 ]
 [0.74665916 0.28074414 0.16825745 0.88652647 0.6827763  0.35453886
  0.20299837 0.41717243 0.24516243 0.08725023]
 [0.8338808  0.20221913 0.54750735 0.5769887  0.3818979  0.29187888
  0.24689856 0.31672472 0.42218822 0.31682974]
 [0.71495587 0.30145574 0.5680796  0.7251078  0.39509842 0.15157706
  0.14903212 0.44948766 0.327242   0.20516118]
 [0.7467251  0.31685805 0.47111696 0.53459054 0.6876789  0.37420863
  0.5181893  0.5396865  0.5557188  0.35288036]
 [0.63715106 0.40968353 0.7489704  0.10899225 0.11995608 0.7848108
  0.63711286 0.28593087 0.6717669  0.85816884]
 [0.5490341  0.48888528 0.3040393  0.7288511  0.76478934 0.3896652
  0.4692509  0.66294    0.4373656  0.21617171]]


In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(100,10))
dense = Dense(units=1,activation='sigmoid')
Y = dense(x)

print(Y.numpy())

[[0.72363496]
 [0.06840473]
 [0.39578187]
 [0.8915695 ]
 [0.36940137]
 [0.51193726]
 [0.7105751 ]
 [0.30639216]
 [0.64311886]
 [0.4839008 ]
 [0.44180974]
 [0.5172941 ]
 [0.2976653 ]
 [0.16579169]
 [0.5609587 ]
 [0.9268236 ]
 [0.30140227]
 [0.48821083]
 [0.24793735]
 [0.63892615]
 [0.30851117]
 [0.922554  ]
 [0.40824938]
 [0.47693822]
 [0.77112216]
 [0.22391045]
 [0.9658133 ]
 [0.36151707]
 [0.50270313]
 [0.66085356]
 [0.52692205]
 [0.52451587]
 [0.3887232 ]
 [0.77863777]
 [0.10420334]
 [0.41971874]
 [0.14283153]
 [0.18285912]
 [0.16460285]
 [0.73854226]
 [0.42474225]
 [0.19625461]
 [0.7735795 ]
 [0.4570467 ]
 [0.7258477 ]
 [0.55900013]
 [0.9760511 ]
 [0.1299735 ]
 [0.76278275]
 [0.47607127]
 [0.5669937 ]
 [0.9314403 ]
 [0.6535943 ]
 [0.39928433]
 [0.86036885]
 [0.4148752 ]
 [0.14350456]
 [0.40553176]
 [0.7595955 ]
 [0.18627498]
 [0.14299417]
 [0.46723026]
 [0.68027395]
 [0.05595556]
 [0.13502619]
 [0.33622342]
 [0.3897165 ]
 [0.27258134]
 [0.6573467 ]
 [0.8714031 ]
 [0.57349086]
 [0.32

In [8]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Dense(units=10,activation='relu'))
model.add(Dense(units=5,activation='relu'))
model.add(Dense(units=1,activation='sigmoid'))

x = tf.random.normal(shape=(10,1))
Y = model(x)
print(Y.numpy())

[[0.31943303]
 [0.46416336]
 [0.44489262]
 [0.5012155 ]
 [0.5005002 ]
 [0.5005568 ]
 [0.34718585]
 [0.4209372 ]
 [0.5010895 ]
 [0.32347628]]


In [11]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape=(1,5),minval=-10,maxval=10)
softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value,axis=1)
print(softmax_sum.numpy())

[1.]


In [14]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
dense = Dense(units=8,activation='softmax')
Y = dense(logit)
Y_sum = tf.reduce_sum(Y,axis=1)
print(Y_sum.numpy())

[1.         0.9999999  0.99999994 0.99999994 1.         1.
 1.         0.99999994]


In [16]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel,self).__init__()

        self.dense1 = Dense(units=8,activation='relu')
        self.dense2 = Dense(units=5,activation='relu')
        self.dense3 = Dense(units=4,activation='softmax')

    def call(self,x):
        x = self.dense1(x)
        x = self.dense2(x)
        x = self.dense3(x)

        return x

model = TestModel()
x =tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
Y = model(x)
print(Y.numpy())
print(tf.reduce_sum(Y,axis=1).numpy())


[[8.97337437e-01 1.02431521e-01 1.12940279e-05 2.19718873e-04]
 [7.56763279e-01 2.42057204e-01 6.90149536e-05 1.11051020e-03]
 [5.82526982e-01 4.07269895e-01 5.13865263e-04 9.68923327e-03]
 [6.22912228e-01 1.51947558e-01 1.08929858e-01 1.16210386e-01]
 [6.28387988e-01 3.02617222e-01 3.47145237e-02 3.42803337e-02]
 [5.99126220e-01 3.93102497e-01 6.28378126e-04 7.14289490e-03]
 [2.38278463e-01 2.53721744e-01 2.43059561e-01 2.64940262e-01]
 [3.46485525e-01 3.25375974e-01 1.32428542e-01 1.95709959e-01]]
[0.99999994 1.         0.99999994 1.         1.0000001  1.
 1.         1.        ]


In [20]:
from tensorflow.keras.losses import MeanSquaredError
import tensorflow as tf

loss_object = MeanSquaredError()
batch_size = 32
predictions = tf.random.normal(shape=(batch_size,1))
labels = tf.random.normal(shape=(batch_size,1))
Y = loss_object(labels,predictions)

print(Y.numpy())
mse_manual = tf.reduce_mean(tf.math.pow(labels-predictions,2))
print(mse_manual.numpy())

1.609683
1.609683
