In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N , n_feature = 8,10

x = tf.random.normal(shape=(N,n_feature))

n_neuron = 3

dense = Dense(units=n_neuron,activation='sigmoid')
Y = dense(x)

W,B = dense.get_weights()

print('====== Input/weight/bias=====')
print("x: ",x.shape)
print("W: ",W.shape)
print("B: ",B.shape)
print("Y: ",Y.shape)

====== Input/weight/bias=====
x:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


In [10]:
import tensorflow as tf
import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N , n_feature = 4,10

X = tf.random.normal(shape=(N,n_feature))

n_neuron = 3

dense = Dense(units=n_neuron,activation='sigmoid')
Y_tf = dense(X)

W,B = dense.get_weights()
print("Y(tensorflow): \n",Y_tf.numpy())

#calculate with matrix multiplication
z = matmul(X,W) +B
Y_man_matmul = 1/(1+exp(-z))
print("Y(with matrix multiplication: \n", Y_man_matmul.numpy())

#calculate with dot products
Y_man_vec = np.zeros(shape=(N,n_neuron))
for x_idx in range(N):
    x = X[x_idx]

    for nu_idx in range(n_neuron):
        w,b = W[:,nu_idx], B[nu_idx]

        z = tf.reduce_sum(x*w) +b
        a = 1/(1+np.exp(-z))
        Y_man_vec[x_idx,nu_idx] = a

print("Y(with dot products): \n",Y_man_vec)

Y(tensorflow): 
 [[0.33065623 0.34015274 0.44794303]
 [0.43847492 0.34112412 0.16789982]
 [0.18151346 0.16297105 0.41146517]
 [0.6552995  0.7116999  0.4493179 ]]
Y(with matrix multiplication: 
 [[0.33065623 0.3401527  0.447943  ]
 [0.43847495 0.34112412 0.16789982]
 [0.18151343 0.16297106 0.41146514]
 [0.6552995  0.71169996 0.4493179 ]]
Y(with dot products): 
 [[0.33065622 0.34015271 0.447943  ]
 [0.43847492 0.34112413 0.16789982]
 [0.18151342 0.16297107 0.41146515]
 [0.65529946 0.71169993 0.4493179 ]]
