<a href="https://colab.research.google.com/github/moosangt/Git-tutorial/blob/master/%EB%94%A5%EB%9F%AC%EB%8B%9D2(%EC%97%B0%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8,10

x = tf.random.normal(shape=(N,n_feature))

n_neuron = 3

dense = Dense(units=n_neuron, activation='sigmoid')

Y = dense(x)

W,B = dense.get_weights()
print('====== Input/weight/bias=====')
print("x: ",x.shape)
print("W: ",W.shape)
print("B: ",B.shape)
print("Y: ",Y.shape)

====== Input/weight/bias=====
x:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


In [ ]:
import tensorflow as tf
import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4,10

X= tf.random.normal(shape=(N,n_feature))

n_neuron = 3

dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W,B = dense.get_weights()
print("Y(tensorflow): \n",Y_tf.numpy())

#calculate with matrix multiplication
z = matmul(X,W) +B
Y_man_matmul = 1/(1+exp(-z))
print("Y(with matrix multiplication: \n", Y_man_matmul.numpy())

#calculate with dot products
Y_man_vec = np.zeros(shape=(N,n_neuron))
for x_idx in range(N):
    x = X[x_idx]

    for nu_idx in range(n_neuron):
        w,b = W[:,nu_idx], B[nu_idx]

        z = tf.reduce_sum(x*w) +b
        a = 1/(1+np.exp(-z))
        Y_man_vec[x_idx,nu_idx] = a

print("Y(with dot products): \n",Y_man_vec)

Y(tensorflow): 
 [[0.73726714 0.7835269  0.6664721 ]
 [0.4813283  0.6863082  0.5744035 ]
 [0.502727   0.52037406 0.22439602]
 [0.38578907 0.4847823  0.64159214]]
Y(with matrix multiplication: 
 [[0.73726714 0.7835269  0.66647214]
 [0.48132837 0.6863082  0.5744035 ]
 [0.502727   0.52037406 0.22439602]
 [0.38578907 0.48478237 0.6415922 ]]
Y(with dot products): 
 [[0.73726716 0.78352686 0.66647207]
 [0.48132833 0.68630821 0.57440352]
 [0.50272694 0.52037402 0.22439603]
 [0.38578907 0.4847823  0.64159221]]
