In [6]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N,n_H,n_W,n_c = 1,5,5,3
n_filter = 4
k_size = 4

images = tf.random.uniform(minval=0, maxval=1,shape=(N,n_H,n_W,n_c))
conv = Conv2D(filters=n_filter,kernel_size = k_size,activation ='sigmoid')

Y = conv(images)
W,B = conv.get_weights()

Y = np.transpose(Y.numpy().squeeze(),(2,0,1))
print("Y(Tensorflow): \n",Y)

images = images.numpy().squeeze()

y_man = np.zeros(shape=(n_H-k_size+1,n_W-k_size+1,n_filter))
for c in range(n_filter):
    c_W  = W[:,:,:,c]
    c_b = B[c]
    for h in range(n_H-k_size+1):
        for w in range(n_W-k_size+1):
            window = images[h:h+k_size,w:w+k_size,:]
            conv = np.sum(window *c_W) + c_b
            conv = 1/(1+np.exp(-conv))

            y_man[h,w,c] = conv
print("Y(Manual) : \n",np.transpose(y_man,(2,0,1)))

Y(Tensorflow): 
 [[[0.4326165  0.39113498]
  [0.4702639  0.42622244]]

 [[0.39412126 0.44880417]
  [0.30472556 0.3048795 ]]

 [[0.7592881  0.63312644]
  [0.73444057 0.7969708 ]]

 [[0.36995757 0.6165554 ]
  [0.32513016 0.40639478]]]
Y(Manual) : 
 [[[0.43261649 0.39113495]
  [0.47026391 0.42622245]]

 [[0.39412127 0.44880419]
  [0.30472555 0.30487949]]

 [[0.75928809 0.63312645]
  [0.73444056 0.7969708 ]]

 [[0.36995755 0.6165554 ]
  [0.32513017 0.4063948 ]]]


In [10]:
import tensorflow as tf

import numpy as np

from tensorflow.keras.layers import Conv2D

N,n_H,n_W,n_c = 1,6,6,3

n_filter = 5
k_size = 5

images = tf.random.uniform(minval=0,maxval=1,shape=(N,n_H,n_W,n_c))
conv = Conv2D(filters=n_filter,kernel_size=k_size,activation='sigmoid')
Y = conv(images)
W,B = conv.get_weights()

Y = np.transpose(Y.numpy().squeeze(),(2,0,1))
print("Y(Tensorflow): \n",Y)

images = images.numpy().squeeze()

y_man = np.zeros(shape=(n_H-k_size+1,n_H-k_size+1,n_filter))
for c in range(n_filter):
    c_W = W[:,:,:,c]
    c_b = B[c]
    for h in range(n_H-k_size+1):
        for w in range(n_W-k_size+1):
            window = images[h:h+k_size,w:w+k_size,:]
            conv = np.sum(window*c_W) + c_b
            conv = 1/(1+np.exp(-conv))

            y_man[h,w,c] = conv

print("Y(Manual) : \n",np.transpose(y_man,(2,0,1)))

Y(Tensorflow): 
 [[[0.6151573  0.56047636]
  [0.43710792 0.49931574]]

 [[0.5885865  0.50160116]
  [0.48080778 0.48224613]]

 [[0.34083745 0.36857998]
  [0.4152573  0.38504845]]

 [[0.5026523  0.42817014]
  [0.43958002 0.5042764 ]]

 [[0.43610978 0.50281376]
  [0.50236523 0.41284764]]]
Y(Manual) : 
 [[[0.61515731 0.56047637]
  [0.4371079  0.49931578]]

 [[0.58858654 0.50160116]
  [0.48080774 0.48224614]]

 [[0.34083743 0.36857998]
  [0.41525727 0.38504839]]

 [[0.50265228 0.42817012]
  [0.43958002 0.50427639]]

 [[0.43610974 0.50281375]
  [0.50236527 0.41284763]]]


In [14]:
import numpy as np

from tensorflow.keras.layers import Conv2D
import tensorflow as tf

N,n_H,n_W,n_C = 1,5,5,3
n_filter = 3
k_size = 3

images = tf.random.uniform( minval=0, maxval=1,shape=(N,n_H,n_W,n_C))
conv = Conv2D(filters=n_filter,kernel_size=k_size,activation='sigmoid')
Y = conv(images)

W,B = conv.get_weights()
Y = np.transpose(Y.numpy().squeeze(),(2,0,1))
print("Y(Tensorflow): \n",Y)

images = images.numpy().squeeze()
y_man = np.zeros(shape=(n_H-k_size+1,n_W-k_size+1,n_filter))
for c in range(n_filter):
    c_W = W[:,:,:,c]
    c_b = B[c]
    for h in range(n_H-k_size+1):
        for w in range(n_W-k_size+1):
            window = images[h:h+k_size,w:w+k_size,:]
            conv = np.sum(window*c_W)+c_b
            conv = 1/(1+np.exp(-conv))

            y_man[h,w,c] = conv

print("Y(Manual) : \n",np.transpose(y_man,(2,0,1)))

Y(Tensorflow): 
 [[[0.4536098  0.40139675 0.42886406]
  [0.34668463 0.33613423 0.56757766]
  [0.42761242 0.33344156 0.45347562]]

 [[0.3363797  0.44870397 0.3899362 ]
  [0.46152958 0.36147776 0.2644221 ]
  [0.3460961  0.3925851  0.37277836]]

 [[0.4406285  0.3990475  0.3173548 ]
  [0.5650134  0.3731245  0.44428322]
  [0.39549917 0.53071064 0.4436907 ]]]
Y(Manual) : 
 [[[0.45360978 0.40139679 0.42886406]
  [0.34668463 0.33613421 0.56757768]
  [0.42761242 0.33344152 0.4534756 ]]

 [[0.3363797  0.44870396 0.38993621]
  [0.46152958 0.36147775 0.26442211]
  [0.3460961  0.39258512 0.37277833]]

 [[0.44062849 0.39904747 0.31735479]
  [0.56501343 0.37312446 0.44428323]
  [0.39549916 0.53071061 0.4436907 ]]]


In [22]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N,n_H,n_W,n_C = 1,10,10,3
n_filter = 9
k_size = 9

images = tf.random.uniform(minval=0,maxval=1,shape=(N,n_H,n_W,n_C))
conv = Conv2D(filters=n_filter,kernel_size=k_size,activation='sigmoid')
Y =conv(images)

W,B = conv.get_weights()
Y = np.transpose(Y.numpy().squeeze(),(2,0,1))
print("Y(Tensorflow): \n",Y,Y.shape)

images = images.numpy().squeeze()

y_man = np.zeros(shape=(n_H-k_size+1,n_W-k_size+1,n_filter))
for c in range(n_filter):
    c_W = W[:,:,:,c]
    c_b = B[c]
    for h in range(n_H-k_size+1):
        for w in range(n_W-k_size+1):
            window = images[h:h+k_size,w:w+k_size,:]
            conv = np.sum(window*c_W)+c_b
            conv = 1/(1+np.exp(-conv))

            y_man[h,w,c] = conv

print("Y(Manual) : \n",np.transpose(y_man,(2,0,1)))

Y(Tensorflow): 
 [[[0.44675356 0.453881  ]
  [0.42321873 0.37797028]]

 [[0.4186343  0.3696295 ]
  [0.44815895 0.459071  ]]

 [[0.6303796  0.49191555]
  [0.50329304 0.5404242 ]]

 [[0.48269606 0.36997014]
  [0.41078144 0.5061861 ]]

 [[0.51694983 0.44519097]
  [0.4128707  0.4574507 ]]

 [[0.31716645 0.2864902 ]
  [0.32119778 0.33331883]]

 [[0.3944539  0.40825018]
  [0.38934898 0.4756312 ]]

 [[0.5502739  0.27551183]
  [0.38011315 0.4794712 ]]

 [[0.29932702 0.3192799 ]
  [0.3230114  0.3417638 ]]] (9, 2, 2)
Y(Manual) : 
 [[[0.44675356 0.45388099]
  [0.42321867 0.37797027]]

 [[0.41863426 0.36962953]
  [0.44815891 0.45907102]]

 [[0.63037956 0.49191556]
  [0.50329299 0.54042421]]

 [[0.48269604 0.36997015]
  [0.41078144 0.50618612]]

 [[0.5169498  0.44519098]
  [0.41287069 0.45745071]]

 [[0.3171664  0.28649027]
  [0.32119778 0.33331876]]

 [[0.39445391 0.4082502 ]
  [0.38934904 0.4756312 ]]

 [[0.55027395 0.27551182]
  [0.38011313 0.47947117]]

 [[0.299327   0.3192799 ]
  [0.32301135 0