In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L,f,s = 10,2,1

x = tf.random.normal((1,L,1))
pool_max = MaxPooling1D(pool_size=f,strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape,x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros((L-f+1,))
for i in range(L-f+1):
    window = x[i:i+f]
    pooled_max_man[i] = np.max(window)

print("pooled_max(Manaul): {}\n{}".format(pooled_max_man.shape,
                                              pooled_max_man))

x: (1, 10, 1)
[ 0.1704281   2.4242337  -2.3354197  -0.4934584   0.39336824 -0.11243726
  0.01054422 -0.7379591   0.12254206 -1.7407727 ]
pooled_max(Tensorflow): (1, 9, 1)
[ 2.4242337   2.4242337  -0.4934584   0.39336824  0.39336824  0.01054422
  0.01054422  0.12254206  0.12254206]
pooled_max(Manaul): (9,)
[ 2.42423368  2.42423368 -0.49345839  0.39336824  0.39336824  0.01054422
  0.01054422  0.12254206  0.12254206]


In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L,f,s = 10,2,1

x = tf.random.normal(shape=(1,L,1))
pool_avg = AveragePooling1D(pool_size=f,strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape,x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L-f+1,))
for i in range(L-f+1):
    window = x[i:i+f]
    pooled_avg_man[i] = np.mean(window)

print("pooled_max(Manaul): {}\n{}".format(pooled_avg_man.shape,
                                              pooled_avg_man))

x: (1, 10, 1)
[-0.0449764  -0.175127    0.37913737 -0.9076251  -0.32605922 -0.38582018
 -0.22939     0.42538658  0.78930354 -0.5515782 ]
pooled_max(Tensorflow): (1, 9, 1)
[-0.1100517   0.10200518 -0.26424384 -0.61684215 -0.3559397  -0.3076051
  0.09799829  0.60734504  0.11886266]
pooled_max(Manaul): (9,)
[-0.1100517   0.10200518 -0.26424384 -0.61684215 -0.35593969 -0.30760509
  0.09799829  0.60734504  0.11886266]


In [7]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N,n_H,n_W,n_C = 1,5,5,1
f,s = 2,1

x = tf.random.normal(shape=(N,n_H,n_W,n_C))
pool_max= MaxPooling2D(pool_size=f,strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape,x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H-f+1,n_W-f+1))
for i in range(n_H-f+1):
    for j in range(n_W-f+1):
        window = x[i:i+f,j:j+f]
        pooled_max_man[i,j] = np.max(window)

print("pooled_max_man(Manual): {}\n{}".format(pooled_max_man.shape,
                                              pooled_max_man))      

x: (1, 5, 5, 1)
[[ 1.5423054  -0.1246912  -2.4318979  -1.0320088  -1.6265986 ]
 [ 0.99066556 -0.03801355  1.3206733  -1.1394864   1.958128  ]
 [-0.88790005  1.2905633  -1.9442348  -1.0059961  -1.1663462 ]
 [ 0.19878432  0.02587679  1.3704551  -0.32782426 -0.22121829]
 [-0.20643164  0.39385644 -0.44372848  0.80958986  0.46786687]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[ 1.5423054   1.3206733   1.3206733   1.958128  ]
 [ 1.2905633   1.3206733   1.3206733   1.958128  ]
 [ 1.2905633   1.3704551   1.3704551  -0.22121829]
 [ 0.39385644  1.3704551   1.3704551   0.80958986]]
pooled_max_man(Manual): (4, 4)
[[ 1.54230535  1.32067335  1.32067335  1.95812798]
 [ 1.29056334  1.32067335  1.32067335  1.95812798]
 [ 1.29056334  1.37045515  1.37045515 -0.22121829]
 [ 0.39385644  1.37045515  1.37045515  0.80958986]]


In [8]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N,n_H,n_W,n_C = 1,5,5,1
f,s = 2,1

x = tf.random.normal(shape=(N,n_H,n_W,n_C))
pool_avg= AveragePooling2D(pool_size=f,strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape,x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H-f+1,n_W-f+1))
for i in range(n_H-f+1):
    for j in range(n_W-f+1):
        window = x[i:i+f,j:j+f]
        pooled_avg_man[i,j] = np.mean(window)

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                              pooled_avg_man)) 

x: (1, 5, 5, 1)
[[-0.20613635  0.24167645  1.0845513   0.06260689  0.24392122]
 [ 0.07692021 -1.2386882  -0.8325956   1.4106175   0.96307737]
 [-0.4048499   0.6369359   0.0932126  -0.8699887   0.70382714]
 [-1.4973603  -0.9575894  -0.16005212 -0.38602665 -0.43573347]
 [ 1.845798   -2.0030587   0.51334506 -0.6443701   1.7677227 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[-0.28155696 -0.18626401  0.43129504  0.67005575]
 [-0.23242049 -0.33528382 -0.04968855  0.55188334]
 [-0.5557159  -0.09687325 -0.33071372 -0.2469804 ]
 [-0.6530526  -0.6518388  -0.16927595  0.07539812]]
pooled_avg(Manual): (4, 4)
[[-0.28155696 -0.18626401  0.43129504  0.67005575]
 [-0.23242049 -0.33528382 -0.04968855  0.55188334]
 [-0.55571592 -0.09687325 -0.33071372 -0.2469804 ]
 [-0.65305263 -0.65183878 -0.16927595  0.07539812]]
