In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W ,n_C = 32,28,28,5
n_filter = 10
k_size =3

images = tf.random.uniform(minval=0,maxval=1,
                           shape=(N, n_H, n_W ,n_C))

conv = Conv2D(filters=n_filter,kernel_size=k_size)
Y =conv(images)

W,B = conv.get_weights()


print(images.shape)
print(W.shape)
print(B.shape)
print(Y.shape)

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


In [19]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W ,n_C = 1,5,5,1
n_filter = 1
k_size =3

images = tf.random.uniform(minval=0,maxval=1,
                           shape=(N, n_H, n_W ,n_C))

conv = Conv2D(filters=n_filter,kernel_size=k_size)
y =conv(images)
print("Y(Tensorflow): \n",y.numpy().squeeze())
W,B = conv.get_weights()


images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H -k_size +1, n_W - k_size +1))
for i in range(n_H-k_size +1):
    for j in range(n_W-k_size +1):
        window = images[i: i+k_size,j: j+k_size]
        y_man[i,j] = np.sum(window * W) +B

print("Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[0.25779635 0.45785934 0.5344299 ]
 [0.83379513 0.55730975 0.31889164]
 [0.30715942 0.763001   0.3379666 ]]
Y(Manual): 
 [[0.25779635 0.45785934 0.53442991]
 [0.83379513 0.55730975 0.31889164]
 [0.30715942 0.76300102 0.33796656]]


In [21]:
import tensorflow as tf
import numpy as np

from tensorflow.keras.layers import Conv2D

N, n_H, n_W ,n_C = 1,5,5,3
n_filter = 1
k_size =3

images = tf.random.uniform(minval=0,maxval=1,
                           shape=(N, n_H, n_W ,n_C))

conv = Conv2D(filters=n_filter,kernel_size=k_size)
y =conv(images)
print("Y(Tensorflow): \n",y.numpy().squeeze())
W,B = conv.get_weights()


images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H -k_size +1, n_W - k_size +1))
for i in range(n_H-k_size +1):
    for j in range(n_W-k_size +1):
        window = images[i: i+k_size,j: j+k_size,:]
        y_man[i,j] = np.sum(window * W) +B

print("Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[0.9247406  0.575575   0.8550794 ]
 [1.01948    0.26542187 0.55927753]
 [0.9826498  0.43708143 0.48041975]]
Y(Manual): 
 [[0.92474049 0.57557499 0.85507935]
 [1.01947987 0.26542181 0.55927753]
 [0.9826498  0.43708137 0.4804197 ]]
