<a href="https://colab.research.google.com/github/moosangt/Git-tutorial/blob/master/%EB%94%A5%EB%9F%AC%EB%8B%9D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.constant([[10.]])

dense = Dense(units=1)

Y_tf = dense(x)

W, B = dense.get_weights() 

y_man = tf.linalg.matmul(x,W) +B

print("=============Input/Weight/Bias ======")
print("x: {}\n{}\n".format(x.shape,x.numpy()))
print("W: {}\n{}\n".format(W.shape,W))
print("B: {}\n{}\n".format(B.shape,B))

print("======= Output ======")
print()

=============Input/Weight/Bias ======
x: (1, 1)
[[10.]]

W: (1, 1)
[[-0.40588498]]

B: (1,)
[0.]

======= Output ======



In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]])

w,b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

dense = Dense(units=1,
              activation = 'linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

y_tf = dense(x)
print(y_tf)

W,B = dense.get_weights()
print(W,B)

print("W: {}\n {}\n".format(W.shape, W))
print("B: {}\n {}\n".format(B.shape, B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
[[10.]] [20.]
W: (1, 1)
 [[10.]]

B: (1,)
 [20.]



In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1,10))

dense = Dense(units=1)

y_tf = dense(x)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) +B

print("=============Input/Weight/Bias ======")
print("x: {}\n{}\n".format(x.shape,x.numpy()))
print("W: {}\n{}\n".format(W.shape,W))
print("B: {}\n{}\n".format(B.shape,B))

print("======= Output ======")
print("y(tensorflow): {}\n{}\n".format(y_tf.shape,y_tf.numpy()))
print("y(Matnual): {}\n{}\n".format(y_man.shape,y_man.numpy()))

=============Input/Weight/Bias ======
x: (1, 10)
[[0.5881008  0.35380745 0.41927886 0.04938912 0.38531673 0.13941681
  0.9649862  0.02895594 0.52298534 0.9120922 ]]

W: (10, 1)
[[-0.03783458]
 [-0.31882733]
 [-0.5191404 ]
 [ 0.2395972 ]
 [-0.62982386]
 [-0.5919173 ]
 [ 0.07855642]
 [-0.27444577]
 [-0.00127167]
 [-0.70240265]]

B: (1,)
[0.]

======= Output ======
y(tensorflow): (1, 1)
[[-1.2395521]]

y(Matnual): (1, 1)
[[-1.2395521]]



In [ ]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1,5))

#activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

#forward propagation(tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

#forward propagation(matmul)

y_sigmoid_man = 1/ (1+exp(-x))
y_tanh_man = (exp(x) - exp(-x))/(exp(x) + exp(-x))
y_relu_man = maximum(x,0)


print("x: {}\n{}".format(x.shape, x.numpy()))

print("simoid(tensorflow) : {}\n{}\n".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("simoid(matmul) : {}\n{}\n".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("tanh(tensorflow) : {}\n{}\n".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("tanh(matmul) : {}\n{}\n".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("relu(tensorflow) : {}\n{}\n".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("relu(matmul) : {}\n{}\n".format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[-1.4278189 -1.5112729 -1.6437404 -0.0502107 -1.6392517]]
simoid(tensorflow) : (1, 5)
[[0.19343874 0.18075019 0.16195673 0.48744997 0.16256693]]

simoid(matmul) : (1, 5)
[[0.19343875 0.18075024 0.16195674 0.48744994 0.16256692]]

tanh(tensorflow) : (1, 5)
[[-0.8912188  -0.9071647  -0.92799366 -0.05016855 -0.92736787]]

tanh(matmul) : (1, 5)
[[-0.8912187  -0.90716475 -0.9279936  -0.05016853 -0.9273679 ]]

relu(tensorflow) : (1, 5)
[[0. 0. 0. 0. 0.]]

relu(matmul) : (1, 5)
[[0. 0. 0. 0. 0.]]



In [ ]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1,5))

#imp. artificial neurons

dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation

y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with sigmoid: {}\n{}".format(y_sigmoid.shape,y_sigmoid.numpy()))
print("AN with tanh: {}\n{}".format(y_tanh.shape,y_tanh.numpy()))
print("AN with relu: {}\n{}".format(y_relu.shape,y_relu.numpy()))

#forward propagation(manual)
print("\n=========\n")

W,B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x,W) +B
a = 1/ (1+exp(-z))

print("Activation value(tensorflow): {}\n{}".format(y_sigmoid.shape,y_sigmoid.numpy()))
print("Activation value(manual): {}\n{}".format(a.shape,a.numpy()))

AN with sigmoid: (1, 1)
[[0.5060678]]
AN with tanh: (1, 1)
[[-0.23054066]]
AN with relu: (1, 1)
[[0.30051044]]


Activation value(tensorflow): (1, 1)
[[0.5060678]]
Activation value(manual): (1, 1)
[[0.5060679]]


In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp,maximum

# activation = 'sigmoid'
# activation = 'tanh'
activation = 'relu'

x  = tf.random.normal(shape=(1,5))

dense = Dense(units=1,activation=activation)

y_tf = dense(x)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) +B
if activation =='sigmoid':
    y_man = 1/(1+exp(-y_man))
elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man))/(exp(y_man) + exp(-y_man))
elif activation == 'relu':
    y_man = maximum(y_man,0)

print("Actiavation: ", activation)
print("y_tf: {}\n{}\n".format(y_tf.shape,y_tf.numpy()))
print("y_man: {}\n{}\n".format(y_man.shape,y_man.numpy()))

Actiavation:  relu
y_tf: (1, 1)
[[2.0377703]]

y_man: (1, 1)
[[2.0377703]]



In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_features = 16,10 #set input params
x = tf.random.normal(shape=(N,n_features)) # generate minibatch


dense = Dense(units=1,activation='relu') #an An
y = dense(x)

W,B = dense.get_weights()

print("Shape of x: {}".format(x.shape))
print("Shape of W: {}".format(W.shape))
print("Shape of B: {}".format(B.shape))

Shape of x: (16, 10)
Shape of W: (10, 1)
Shape of B: (1,)


In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_features = 8,10 #set input params
x = tf.random.normal(shape=(N,n_features)) # generate minibatch

dense = Dense(units=1,activation='sigmoid') #an An
y_tf = dense(x) #forward propagation(Tensorflow)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W)+B
y_man = 1/(1+tf.math.exp(-y_man))

print("Output(Tensorflow): \n",y_tf.numpy())
print("Output(Manual): \n",y_man.numpy())

Output(Tensorflow): 
 [[0.7156338 ]
 [0.41357368]
 [0.6309638 ]
 [0.11467037]
 [0.07560831]
 [0.65223426]
 [0.26671842]
 [0.5512584 ]]
Output(Manual): 
 [[0.7156338 ]
 [0.4135737 ]
 [0.6309638 ]
 [0.1146704 ]
 [0.07560832]
 [0.65223426]
 [0.2667184 ]
 [0.5512584 ]]
