In [9]:
import math

import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N,n_H,n_W,n_C = 1,5,5,3
f,s = 2,2

x = tf.random.normal(shape=(N,n_H,n_W,n_C))
#print("x: {}\n{}".format(x.shape,
#                       np.transpose(x.numpy().squeeze(),(2,0,1))))

pool_max = MaxPooling2D(pool_size=f,strides=s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(),(2,0,1))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                             pooled_max_t))

x = x.numpy().squeeze()
n_H_ = math.floor((n_H-f)/s +1)
n_W_ = math.floor((n_W-f)/s +1)
pooled_max_man = np.zeros(shape=(n_H_,n_W_,n_C))

for c in range(n_C):
    c_image = x[:,:,c]

    h_ = 0
    for h in range(0,n_H-f+1,s):
        w_ = 0
        for w in range(0,n_W-f+1,s):
            window = c_image[h:h+f,w:w+f]
            pooled_max_man[h_,w_,c] = np.max(window)
            
            w_ +=1
        h_ +=1  

pooled_max_man_t = np.transpose(pooled_max_man,(2,0,1))

print("pooled_max_man(Manual): {}\n{}".format(pooled_max_man.shape,
                                             pooled_max_man_t))

pooled_max(Tensorflow): (1, 2, 2, 3)
[[[0.88311017 1.9119071 ]
  [1.3070912  0.8843831 ]]

 [[0.41624916 0.02334776]
  [1.0830271  0.36181232]]

 [[1.3125122  0.6957575 ]
  [0.9156566  0.6125134 ]]]
pooled_max_man(Manual): (2, 2, 3)
[[[0.88311017 1.91190708]
  [1.30709124 0.88438308]]

 [[0.41624916 0.02334776]
  [1.08302712 0.36181232]]

 [[1.31251216 0.69575751]
  [0.91565663 0.61251342]]]


In [22]:
import tensorflow as tf
import numpy as np


from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape=(1,5,5,3))
print(images.shape)
#print(np.transpose(images.numpy().squeeze(),(2,0,1)))

zero_padding = ZeroPadding2D(padding=1)
y = zero_padding(images)
print(y.shape)
#print(np.transpose(y.numpy().squeeze(),(2,0,1)))


(1, 5, 5, 3)
(1, 7, 7, 3)


In [24]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1,28,28,3))
conv = Conv2D(filters=1,kernel_size=3,padding='same')
y = conv(images)
print(y.shape)

(1, 28, 28, 1)


In [25]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1,28,28,3))
conv = Conv2D(filters=1,kernel_size=3,padding='valid',strides=2)
y = conv(images)
print(y.shape)

(1, 13, 13, 1)


In [27]:
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape=(1,28,28,3))
pool = MaxPooling2D(pool_size=3,strides=2)
y = pool(images)

print(images.shape  )
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)
