In [14]:
import tensorflow as tf
from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)

softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value,axis=1)
print("Logits : \n",logit.numpy())
print("softmax : \n",softmax_value.numpy())

print("sum of softmax values : \n",softmax_sum)

Logits : 
 [[-4.1699362e+00  2.3612995e+00  5.2013283e+00  2.3121834e-01
   1.6945381e+00]
 [-6.9227409e-01 -4.0853715e+00 -2.6292038e+00  7.9202614e+00
   4.9410725e+00]
 [ 3.2250214e-01 -5.1164627e-03  8.4386826e-01 -7.8125620e+00
   1.2115936e+00]
 [-1.6182117e+00  6.8208885e-01  4.8032236e+00 -3.3083010e+00
  -7.1970105e+00]
 [-8.1593342e+00  1.9479923e+00  9.9321175e+00 -9.8748283e+00
  -8.1554203e+00]
 [ 4.5342302e+00 -5.8279037e-02  7.7604713e+00 -3.6307907e+00
   8.8201637e+00]
 [ 5.2697325e+00  5.2805281e+00 -9.9651546e+00  8.9848614e+00
  -8.1110001e-03]
 [ 9.9332352e+00 -4.5375848e+00  6.9509239e+00 -7.7252913e+00
  -9.6820450e+00]]
softmax : 
 [[7.7717923e-05 5.3333584e-02 9.1287142e-01 6.3375048e-03 2.7379783e-02]
 [1.7298195e-04 5.8129622e-06 2.4934627e-05 9.5143121e-01 4.8365101e-02]
 [1.7128636e-01 1.2343543e-01 2.8850225e-01 5.0200651e-05 4.1672572e-01]
 [1.5973151e-03 1.5936702e-02 9.8216516e-01 2.9470952e-04 6.0332159e-06]
 [1.3894226e-08 3.4071444e-04 9.9965930e-01 

In [16]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
dense = Dense(units=8,activation='softmax')

Y = dense(logit)
print(tf.reduce_sum(Y,axis=1))

tf.Tensor(
[0.99999994 0.99999994 1.         0.9999999  0.99999994 1.
 1.0000001  1.        ], shape=(8,), dtype=float32)


In [20]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel,self).__init__()

        self.dense1 = Dense(units=8,activation='relu')
        self.dense2 = Dense(units=5,activation='relu')
        self.dense3 = Dense(units=3,activation='softmax')

    def call(self,x):
        print("x: {}\n{}\n".format(x.shape,x.numpy()))

        x= self.dense1(x)
        print("x: {}\n{}\n".format(x.shape,x.numpy()))

        x= self.dense2(x)
        print("x: {}\n{}\n".format(x.shape,x.numpy()))

        x= self.dense3(x)
        print("x: {}\n{}\n".format(x.shape,x.numpy()))
        print("sum of vectors: {}\n".format(tf.reduce_sum(x,axis=1)))
        return x

model = TestModel()

x = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
Y = model(x)


x: (8, 5)
[[-3.7590098  -9.198626    6.573469   -3.3987188  -2.8476048 ]
 [ 9.814484    1.566555   -4.210603   -2.0576906  -7.376859  ]
 [ 8.51594    -7.8510404  -7.4310303  -9.517157   -5.092664  ]
 [-3.7915206  -0.5153656  -1.0672207  -0.68668556  0.6411381 ]
 [ 1.3055782   0.79042625 -1.4297152  -4.1980124  -7.3538327 ]
 [ 2.0815468  -9.203162    0.40867805 -8.7788725   3.3652802 ]
 [ 6.525011    9.999666    5.3786564  -4.3330646  -8.66292   ]
 [-2.361033    2.3547554   5.7191944   6.63805    -2.686665  ]]

x: (8, 8)
[[ 7.636137    0.40319195  5.8983517   0.          7.427576    0.
   3.2647302   0.        ]
 [ 0.          0.          1.4415803   1.1372914   0.03783187  0.
   0.         12.0856495 ]
 [ 0.          0.          9.614102    0.          7.946767    0.
   0.         13.78667   ]
 [ 0.23126568  0.          0.8976662   0.          0.          0.
   0.11324639  0.        ]
 [ 0.          0.5255349   2.6584408   0.          0.          0.
   0.          6.577398  ]
 [ 0.6074