In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel,self).__init__()

        self.dense1 = Dense(units=8,activation='relu')
        self.dense2 = Dense(units=5,activation='relu')
        self.dense3 = Dense(units=3,activation='softmax')

    def call(self,x):
        x = self.dense1(x)
        x = self.dense2(x)
        x = self.dense3(x)
        return x

model = TestModel()
logit = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
Y = model(logit)

print("Y :\n",Y.numpy())
print("Sum of Y: ",tf.reduce_sum(Y,axis=1))

Y :
 [[9.9750167e-01 9.9159265e-04 1.5067277e-03]
 [9.9965358e-01 3.0500692e-04 4.1496944e-05]
 [9.4206190e-01 5.1943228e-02 5.9949206e-03]
 [8.3710766e-01 1.4217871e-01 2.0713639e-02]
 [8.1574178e-01 1.8408129e-01 1.7687549e-04]
 [9.9995530e-01 3.3377819e-05 1.1286904e-05]
 [9.1318226e-01 6.5411173e-02 2.1406654e-02]
 [8.7099820e-01 4.8770633e-02 8.0231182e-02]]
Sum of Y:  tf.Tensor(
[1.         1.0000001  1.0000001  1.         0.99999994 0.99999994
 1.0000001  1.        ], shape=(8,), dtype=float32)


In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self):
        super(TestModel,self).__init__()

        self.dense1 = Dense(units=10,activation='relu')
        self.dense2 = Dense(units=5,activation='relu')
        self.dense3 = Dense(units=3,activation='softmax')

    def call(self,x):
        x = self.dense1(x)
        x = self.dense2(x)
        x = self.dense3(x)
        return x

model = TestModel()
x = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
Y = model(x)
print(tf.reduce_sum(Y.numpy(),axis=1))


tf.Tensor(
[1.         1.         0.99999994 1.         1.         1.
 1.         1.        ], shape=(8,), dtype=float32)
