In [3]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L,f,s = 8,2,1

x = tf.random.normal(shape=(1,L,1))
pool_max = MaxPooling1D(pool_size=f,strides=s)
pooled_max = pool_max(x)

print("x: {}\n{} ".format(x.shape,x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().flatten()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros((L-f+1,))
for i in range(L-f+1):
    window = x[i:i+f]
    pooled_max_man[i] = np.max(window)

print("pooled_max_man(Manual): {}\n{}".format(pooled_max_man.shape,
                                              pooled_max_man))

x: (1, 8, 1)
[ 1.3174863   0.38601035  1.3486851  -0.15195458  0.6812891  -0.09390097
 -0.5402576  -1.1602627 ] 
pooled_max(Tensorflow): (1, 7, 1)
[ 1.3174863   1.3486851   1.3486851   0.6812891   0.6812891  -0.09390097
 -0.5402576 ]
pooled_max_man(Manual): (7,)
[ 1.31748629  1.34868515  1.34868515  0.68128908  0.68128908 -0.09390097
 -0.54025757]


In [6]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L,f,s = 10,2,1

x = tf.random.normal(shape=(1,L,1))
pool_avg = AveragePooling1D(pool_size=f,strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape,x.numpy().flatten()))
print("pooled_max(Tensorflow) {}\n{}".format(pooled_avg.shape,
                                             pooled_avg.numpy().flatten()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros((L-f+1))
for i in range(L-f+1):
    window = x[i:i+f]
    pooled_avg_man[i] = np.mean(window)

print("pooled_avg_man(Manual) : {}\n{}".format(pooled_avg_man.shape,
                                               pooled_avg_man))

x: (1, 10, 1)
[-0.2862086  -2.356569    0.5773409  -0.5235415   0.31095958 -0.12474933
  0.8322921   0.89085776  0.20506978  1.3073573 ]
pooled_max(Tensorflow) (1, 9, 1)
[-1.3213888  -0.8896141   0.0268997  -0.10629097  0.09310512  0.3537714
  0.8615749   0.54796374  0.75621355]
pooled_avg_man(Manual) : (9,)
[-1.32138884 -0.88961411  0.0268997  -0.10629097  0.09310512  0.35377139
  0.86157489  0.54796374  0.75621355]


In [7]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N,n_H,n_W,n_C = 1,5,5,1

f,s = 2,1

x = tf.random.normal(shape=(N,n_H,n_W,n_C))
pool_max = MaxPooling2D(pool_size=f,strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape,x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H-f+1,n_W-f+1))
for i in range(n_H-f+1):
    for j in range(n_W-f+1):
        window = x[i:i+f,j:j+f]
        pooled_max_man[i,j] = np.max(window)

print("pooled_max_man(Manual): {}\n{}".format(pooled_max_man.shape,
                                              pooled_max_man))  

x: (1, 5, 5, 1)
[[ 0.06553491  0.5595478   1.6352166   1.9195756   0.24874541]
 [-1.4701633  -0.21231773  0.14956959  0.6921979  -0.48028114]
 [ 2.434631    1.0606517   1.4603102   0.46052477  1.1459715 ]
 [-1.5256582   0.08303674  0.94699377  0.11785644 -0.9131438 ]
 [ 0.55032647 -1.215722   -0.38282523  1.2476566  -0.40895134]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[0.5595478  1.6352166  1.9195756  1.9195756 ]
 [2.434631   1.4603102  1.4603102  1.1459715 ]
 [2.434631   1.4603102  1.4603102  1.1459715 ]
 [0.55032647 0.94699377 1.2476566  1.2476566 ]]
pooled_max_man(Manual): (4, 4)
[[0.55954778 1.63521659 1.91957557 1.91957557]
 [2.43463111 1.46031022 1.46031022 1.14597154]
 [2.43463111 1.46031022 1.46031022 1.14597154]
 [0.55032647 0.94699377 1.24765658 1.24765658]]


In [12]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N,n_H,n_W,n_C = 1,5,5,1
f,s = 2,1

x = tf.random.normal(shape=(N,n_H,n_W,n_C))
pool_avg = AveragePooling2D(pool_size=f,strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape,x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H-f+1,n_W-f+1))
for i in range(n_H-f+1):
    for j in range(n_W-f+1):
        window = x[i:i+f,j:j+f]
        pooled_avg_man[i,j] = np.mean(window)

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                              pooled_avg_man)) 


x: (1, 5, 5, 1)
[[ 0.99316543  1.2233137   0.55636543 -0.34729716 -0.6438472 ]
 [ 0.7827462   0.87201303 -1.1082908  -0.10152284  0.19358228]
 [ 1.792376   -0.14244287  1.0347675   1.3415859   3.4598153 ]
 [-0.37502897  1.368393    0.7577825  -0.03091815  1.487092  ]
 [-1.2761407  -0.09170667 -0.6270463  -0.09154415  0.0219079 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[ 0.96780956  0.38585034 -0.25018632 -0.22477123]
 [ 0.82617307  0.16401172  0.29163495  1.2233652 ]
 [ 0.6608243   0.754625    0.7758044   1.5643938 ]
 [-0.09362084  0.35185558  0.00206849  0.34663442]]
pooled_avg(Manual): (4, 4)
[[ 0.96780956  0.38585034 -0.25018632 -0.22477123]
 [ 0.82617307  0.16401172  0.29163495  1.22336519]
 [ 0.6608243   0.75462502  0.7758044   1.56439376]
 [-0.09362084  0.35185558  0.00206849  0.34663442]]
